Dynamically create dropdown on header
algoritmos-iii/algoritmos-iii.github.io pull request #31
Opened 2021-10-05 01:27 UTC by mrti259

Para crear un dropdown en el header con las distintas páginas hay que agregar una categoría `category` en el archivo correspondiente y usar el mismo nombre en las demás páginas pertenecientes a la misma categoría.

2021-10-05 13:34 UTC, julitaras commented
Podemos ver algun screen o una breve demo de como se veria con el nuevo cambio ? Thx

2021-10-05 13:47 UTC, julitaras commented
Me parece que esta bien, no se si sera posible en vez de tener el titulo de `Otros cuatrimestres` poner directamente 

- 2020 2c
- 2021 1c

![image](https://user-images.githubusercontent.com/30576222/136035054-08a79561-9334-4757-ae28-7d9454b76517.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-10-05 at 10 44 32](https://user-images.githubusercontent.com/30576222/136035319-9042418b-3b3c-4715-ac37-3bc8fac87170.png)

https://user-images.githubusercontent.com/30576222/136035329-a5225ce3-58ad-43fd-821f-087e534dcf21.mp4

2021-10-05 20:16 UTC, mrti259 commented
Update: https://mrti259.github.io/algoritmos-iii.github.io/

2021-10-13 22:57 UTC, julitaras commented
Borja, fijate que la idea por la cual surgio esto es que quede todo en la misma linea. 
![image](https://user-images.githubusercontent.com/30576222/137223711-13d3fbef-1dc9-403c-9c81-b7ccaaf852cc.png)

Y eso aca no estaria pasando. Por eso es que acortamos los nombres

2021-10-14 12:46 UTC, julitaras requested changes
comment de arriba

2021-10-14 15:49 UTC, closed without merging